### ISSUE TITLE
Bot re-execute all commands after re-joining the room

### ISSUE THREAD

**Issue by AnassDriate** [mautrix/python#162] opened 2023-09-29 14:30 UTC
Hello,

I'm encountering an issue with the behavior of my bot when it leaves a room and then rejoins. Specifically, the bot re-executes all previous commands and ends up leaving the room again because the last command issued was to leave.

I've explored a couple of potential solutions but haven't found the ideal one yet. Deactivating the sync option, while preventing the bot from autojoining, is not suitable for my use case. I also attempted to forget the room after leaving it, hoping to clear the command history, but even after rejoining and syncing, the bot continues to re-execute all previous commands.

The goal is to ensure that the bot doesn't repeat commands upon rejoining the room while still retaining the ability to autojoin when necessary.

Thank you in advance for any assistance.

Regards,

**Comment by tulir** [comment] 2023-09-29 14:37
Duplicate of #128

**Closed by tulir** 2023-09-29 14:37 UTC
